[build]
  publish = "site"
  command = "curl -LsSf https://astral.sh/uv/install.sh | sh && /opt/buildhome/.local/bin/uv sync && /opt/buildhome/.local/bin/uv run mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.13"
